[project]
name = "rssparser"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.14.3",
    "beautifulsoup4==4.15.0",
    "soupsieve==2.9.2",
    "bencodepy",
    "cryptography==50.0.0",
    "feedparser==6.0.14",
    "gotify",
    "pyaniparser==0.6.1",
    "pymysql==1.2.0",
    "python-telegram-bot==22.8",
    "pytz==2026.3",
    "qbittorrent-api==2026.8.0",
    "requests==2.34.2",
    "sqlalchemy==2.0.51",
    "urllib3==2.7.0",
]
